//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_BD
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DutyPart
    {
        public long DutyOfficer { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public int TheNumberOfEmployees { get; set; }
        public long Warehouse { get; set; }
        public long Connection { get; set; }
        public long Request { get; set; }
    
        public virtual ContactComm ContactComm { get; set; }
        public virtual Duty Duty { get; set; }
        public virtual Request Request1 { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
