//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_BD
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Duty
    {
        public long ID_Duty { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public short Age { get; set; }
        public string Male { get; set; }
        public string Position { get; set; }
    
        public virtual DutyPart DutyPart { get; set; }
    }
}
