//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KR_BDEntities : DbContext
    {
        public KR_BDEntities()
            : base("name=KR_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citizen> Citizen { get; set; }
        public virtual DbSet<ContactComm> ContactComm { get; set; }
        public virtual DbSet<Duty> Duty { get; set; }
        public virtual DbSet<DutyPart> DutyPart { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<NormTableDutyPart> NormTableDutyPart { get; set; }
        public virtual DbSet<NormTableRequest> NormTableRequest { get; set; }
    }
}
