//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_BD
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class NormTableDutyPart
    {
        public string City { get; set; }
        public string District { get; set; }
        public string Expr1 { get; set; }
        public int TheNumberOfEmployees { get; set; }
        public string Telephone { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string TheEssenceOfTheApplication { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReplyDate { get; set; }
    }
}
