//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_BD
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.DutyPart = new ObservableCollection<DutyPart>();
        }
    
        public long IdApplicaton { get; set; }
        public long Citizen { get; set; }
        public string TheEssenceOfTheApplication { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReplyDate { get; set; }
    
        public virtual Citizen Citizen1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DutyPart> DutyPart { get; set; }
    }
}
